require('angular');
require('angular-ui-bootstrap');
require('angular-ui-router');
require('angular-sanitize');
require('ng-focus-if');
require('angular-bootstrap');
require('angular-validation');
require('angular-ui-select');
require('angular-mailto');
import 'bootstrap/dist/css/bootstrap.css';
import '../bower_components/angular/angular.js';
import '../bower_components/angular-validation/dist/angular-validation-rule';